volumes:
  data:

services:
  postgres:
    image: postgres:15.1
    restart: unless-stopped
    environment:
      - POSTGRES_DB=ask
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    volumes:
      - ./postgresql-data:/var/lib/postgresql

  server:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    ports:
      - 8000:8000
    depends_on:
      - postgres