services:
  server:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./ask/db.sqlite3:/usr/src/app/ask/db.sqlite3